version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    networks:
      - bearonboard-network
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=admin1234
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '5672']
      interval: 5s
      timeout: 15s
      retries: 1

  redis:
    image: redis
    container_name: redis
    networks:
      - bearonboard-network

  app:
    build: .
    image: avivi28/bearonboard
    container_name: bearonboard
    depends_on:
      - redis
      - rabbitmq
    links:
      - redis
      - rabbitmq
    ports:
      - 9090:9090
    networks:
      - bearonboard-network

networks:
  bearonboard-network:
    name: bearonboard-network
